### ISSUE TITLE
SourcePath Parameter set doesn't work

### ISSUE THREAD

**Issue by montereyharris** [bentaylorwork/omsAgent#1]
Source Path Parameter set failing and defaulting to Downloadurl. You also can't set workspace values with sourcepath parameter

**Comment by montereyharris** [comment]
I have an edit verison that fixes these issues will submit pull request after I confirm it passes Pester tests

**Comment by bentaylorwork** [comment]
Hi,

I have just looked at it again and can see the issue straight away.

I chopped this function (https://github.com/bentaylorwork/PowerShell/blob/master/Scripts/OMS/Install-OmsAgent.ps1) around and didn't pay as much attention as I should!

Please submit a PR or I will try and find time to fix over the weekend.

Thanks

Ben

**Comment by montereyharris** [comment]
I submitted a pull request.

**Comment by bentaylorwork** [comment]
Hi,

I never received an updated PR. I will fix over the next few days.

Thanks

**Comment by montereyharris** [comment]
I submitted an updated pull request

**Comment by montereyharris** [comment]
I added a change to the $path variable so function doesn't fail when source file is not named default name
